### ISSUE TITLE
run singleton test in isolation

### ISSUE THREAD

**Issue by bsr203** [prometheusresearch/webtest#6]
Hi @andreypopp 

I love to use this project due to its simplicity and stuck with one issue. I like to run flux store tests in isolation, as described in the below links, but not sure how to do it with `webtest`. I tried just requiring this file (https://github.com/kentor/react-flux-testing/blob/master/tests.webpack.js) in my test, but that made it too slow (about 10 sec). How can I do it as described in this post which is set up with Karma.

http://kentor.me/posts/testing-react-and-flux-applications-with-karma-and-webpack/
https://github.com/kentor/react-flux-testing

Please also look at previous issues I raised. 

thanks.
bsr

**Comment by andreypopp** [comment]
Sorry for being unresponsive. Test isolation would be great to have. I'll reopen this issue to track it.

**Comment by bsr203** [comment]
:-) thanks. I am still sticking with webtest. I greatly enjoy it. so minimal, and functional. 

I tried creating a context, and clearing the singleton context but didn't work for me. Mainly I wasn't sure about the regexp to use, and also needed to include some files from my `node_modules` (like scss, jsx which needs babel transform). You may find this thread useful.

https://github.com/webpack/webpack/issues/118

**Comment by bsr203** [comment]
recently using jest exclusively. so don't need this anymore.
