### ISSUE TITLE
further support

### ISSUE THREAD

**Issue by bsr203** [prometheusresearch/webtest#8]
Hi Andrey,

I saw you removed the use of webtest in your `react-forms` package in favor of `mocha`. Can you please advise using `webtest` and future plans.. tx

**Comment by andreypopp** [comment]
Hi,

we are moving to use `webtest` only for the cases where browser environment is needed. For the cases where jsdom based test env is sufficient I recommend using lighter tools such as `mocha`.

We are not discontinuing development of `webtest`.

**Comment by bsr203** [comment]
thanks andrey for explaining the use cases...
